format = """
$container\
$conda\
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$time\
$status\
$character
"""

[character]
success_symbol = '[→](green)'
error_symbol = '[→](red)'

[container]
style=''
format='[$symbol]($style) '
